name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
          
      - name: Build with environment variables
        run: |
          cat > env.js <<EOF
          const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}",
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}"
          };
          const ADMIN_KEY = "${{ secrets.ADMIN_KEY }}";
          EOF
          
      - name: Replace placeholders
        run: |
          sed -i "s|process.env.FIREBASE_API_KEY|\"${{ secrets.FIREBASE_API_KEY }}\"|g" index.html
          sed -i "s|process.env.FIREBASE_AUTH_DOMAIN|\"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"|g" index.html
          # Repeat for all other environment variables
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
